# Generated by Django 6.0.7 on 2026-07-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
