# Generated by Django 6.0.7 on 2026-07-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_longitude_place_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
